#!/bin/bash

vers=$(sw_vers | grep "ProductVersion:" | cut -f2 | cut -f1-2 -d".")

# if [ $vers == "10.9" ]
# then
# 	echo "Installing CLT for Mavericks..."
# 	cd /Volumes/APS/Installers/Mac_Installers/Xcode_lion_ml
# 	hdiutil mount command_line_tools_os_x_mountain_lion_for_xcode__october_2013.dmg
# 	cd /Volumes/Command\ Line\ Tools\ \(Mountain\ Lion\)/
# 	sudo installer -pkg /Volumes/Command\ Line\ Tools\ \(Mountain\ Lion\)/ -target /
# 	hdiutil unmount /Volumes/Command\ Line\ Tools\ \(Mountain\ Lion\)/
# fi

# if [ $vers == "10.8" ]
# then
# 	echo "Installing CLT for Mountain Lion..."
# 	cd /Volumes/APS/Installers/Mac_Installers/Xcode_lion_ml
# 	hdiutil mount xcode452cltools10_86938211a.dmg
# 	cd Command\ Line\ Tools\ \(Mountain\ Lion\)/
# 	sudo installer -pkg Command\ Line\ Tools\ \(Mountain\ Lion\).mpkg
# 	hdiutil unmount /Volumes/Command\ Line\ Tools\ \(Mountain\ Lion\)/
# fi

xcode-select --install

curl -O -L http://sourceforge.net/projects/git-osx-installer/files/git-2.2.1-intel-universal-mavericks.dmg
hdiutil mount git-2.2.1-intel-universal-mavericks.dmg && sudo installer -pkg /Volumes/Git\ 2.2.1\ Mavericks\ Intel\ Universal/git-2.2.1-intel-universal-mavericks.pkg -target / && hdiutil unmount /Volumes/Git\ 2.2.1\ Mavericks\ Intel\ Universal